import * as React from "react";
import { Sparkles } from "lucide-react";

interface ReportSummaryProps {
  summary: string;
  aiAnalysis?: string;
  recommendations?: string[];
}

export function ReportSummary({ summary, aiAnalysis, recommendations }: ReportSummaryProps) {
  return (
    <div className="bg-primary/5 border border-primary/20 rounded-3xl p-6 sm:p-8">
      <div className="flex items-center gap-2 mb-4">
        <Sparkles className="w-5 h-5 text-primary" />
        <span className="text-sm font-semibold uppercase tracking-wider text-primary">AI Clinical Summary</span>
      </div>

      <div className="space-y-6">
        <div>
          <p className="text-foreground font-medium leading-relaxed">{summary}</p>
        </div>
        
        {aiAnalysis && (
          <div>
            <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2">Detailed Analysis</h4>
            <p className="text-sm text-muted-foreground leading-relaxed">{aiAnalysis}</p>
          </div>
        )}

        {recommendations && recommendations.length > 0 && (
          <div>
            <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2">Recommendations</h4>
            <ul className="space-y-2">
              {recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 shrink-0" />
                  {rec}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <div className="mt-6 pt-6 border-t border-primary/10">
        <p className="text-xs text-primary/70">
          This summary was generated by CARE360 AI to help you understand your results. It does not replace professional medical advice. Always consult your doctor.
        </p>
      </div>
    </div>
  );
}
